full_Data.Sparsity(51)=struct('Name','Mean','Entropy',0,'Sparsity', 0,...
        'ORACLE_Entropy',0,'ORACLE_Sparsity', 0,...
        'Context_Entropy',0,'Context_Sparsity',0);
for i=1:50
    full_Data.Sparsity(51)=struct('Name','Mean','Entropy',full_Data.Sparsity(51).Entropy+full_Data.Sparsity(i).Entropy,'Sparsity', full_Data.Sparsity(51).Sparsity+full_Data.Sparsity(i).Sparsity,...
        'ORACLE_Entropy',full_Data.Sparsity(51).ORACLE_Entropy+full_Data.Sparsity(i).ORACLE_Entropy,'ORACLE_Sparsity', full_Data.Sparsity(51).ORACLE_Sparsity+full_Data.Sparsity(i).ORACLE_Sparsity,...
        'Context_Entropy',full_Data.Sparsity(51).Context_Entropy+full_Data.Sparsity(i).Context_Entropy,'Context_Sparsity',full_Data.Sparsity(51).Context_Sparsity+full_Data.Sparsity(i).Context_Sparsity );
end
full_Data.Sparsity(51)=struct('Name','Mean','Entropy',full_Data.Sparsity(51).Entropy/i,'Sparsity', full_Data.Sparsity(51).Sparsity/i,...
        'ORACLE_Entropy',full_Data.Sparsity(51).ORACLE_Entropy/i,'ORACLE_Sparsity', full_Data.Sparsity(51).ORACLE_Sparsity/i,...
        'Context_Entropy',full_Data.Sparsity(51).Context_Entropy/i,'Context_Sparsity',full_Data.Sparsity(51).Context_Sparsity/i );